name: 'Tauri Build'

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Frontend Dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@v0
        with:
          args: ${{ matrix.args }}

      - uses: actions/upload-artifact@v4
        with:
          name: RPCSX-UI
          path: src-tauri/target/release/bundle/appimage/RPCSX_0.1.0_amd64.AppImage
